In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/jiayichen/Files/dystage_extension/daily_clean_ret_v2_with_news.csv')

/var/folders/1k/2y5_6bjx2pj26kpmhsvn1hmh0000gn/T/ipykernel_30819/2877089933.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/jiayichen/Files/dystage_extension/daily_clean_ret_v2_with_news.csv')

In [3]:
df.head()

,datadate,cusip,capgn,divd,eps,ret,size,log_vol,grvol,grshrout,...,m_3m,m_6m,Max_y,Min_y,Rel2High,Rel2low,spread,sp_opclose,ticker,news_text
0,2011-01-03,723484101,0.0,0.0,1.4,0.000724,22.229424,13.838691,1.073191,0.0,...,0.005318,0.121345,42.37,34.5,-0.021005,0.202319,0.5800,-0.08,PNW,NaN
1,2011-01-04,723484101,0.0,0.0,1.4,0.004330,22.233754,13.633325,-0.205365,0.0,...,0.000000,0.096703,42.37,34.5,-0.016757,0.207536,0.4800,0.08,PNW,NaN
2,2011-01-05,723484101,0.0,0.0,1.4,-0.006744,22.227010,13.154641,-0.478685,0.0,...,-0.001208,0.081010,42.37,34.5,-0.023366,0.199420,0.3175,-0.16,PNW,NaN
3,2011-01-06,723484101,0.0,0.0,1.4,0.001931,22.228942,14.486690,1.332049,0.0,...,0.006776,0.083203,42.37,34.5,-0.021477,0.201739,0.4100,0.00,PNW,NaN
4,2011-01-07,723484101,0.0,0.0,1.4,0.003131,22.232072,14.685083,0.198393,0.0,...,0.007966,0.080584,42.37,34.5,-0.018409,0.205507,0.3900,0.06,PNW,NaN

In [5]:
df

,datadate,cusip,capgn,divd,eps,ret,size,log_vol,grvol,grshrout,...,m_3m,m_6m,Max_y,Min_y,Rel2High,Rel2low,spread,sp_opclose,ticker,news_text
0,2011-01-03,723484101,0.0,0.0,1.40,0.000724,22.229424,13.838691,1.073191,0.0,...,0.005318,0.121345,42.37,34.5,-0.021005,0.202319,0.5800,-0.08,PNW,NaN
1,2011-01-04,723484101,0.0,0.0,1.40,0.004330,22.233754,13.633325,-0.205365,0.0,...,0.000000,0.096703,42.37,34.5,-0.016757,0.207536,0.4800,0.08,PNW,NaN
2,2011-01-05,723484101,0.0,0.0,1.40,-0.006744,22.227010,13.154641,-0.478685,0.0,...,-0.001208,0.081010,42.37,34.5,-0.023366,0.199420,0.3175,-0.16,PNW,NaN
3,2011-01-06,723484101,0.0,0.0,1.40,0.001931,22.228942,14.486690,1.332049,0.0,...,0.006776,0.083203,42.37,34.5,-0.021477,0.201739,0.4100,0.00,PNW,NaN
4,2011-01-07,723484101,0.0,0.0,1.40,0.003131,22.232072,14.685083,0.198393,0.0,...,0.007966,0.080584,42.37,34.5,-0.018409,0.205507,0.3900,0.06,PNW,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180468,2020-12-24,N53745100,0.0,0.0,3.56,-0.000221,24.132974,12.451940,-1.261212,0.0,...,0.263513,0.357574,94.48,34.9,-0.040961,1.596275,1.3000,-0.11,LYB,NaN
1180469,2020-12-28,N53745100,0.0,0.0,3.56,-0.000110,24.132863,13.585549,1.133609,0.0,...,0.240821,0.332836,94.48,34.9,-0.041067,1.595989,2.2100,-1.64,LYB,NaN
1180470,2020-12-29,N53745100,0.0,0.0,3.56,-0.012327,24.120536,13.506346,-0.079203,0.0,...,0.241640,0.308724,94.48,34.9,-0.052815,1.564183,2.4800,-1.23,LYB,NaN
1180471,2020-12-30,N53745100,0.0,0.0,3.56,0.017502,24.138037,13.476184,-0.030162,0.0,...,0.256158,0.327900,93.86,34.9,-0.029725,1.609456,2.1650,1.63,LYB,NaN
1180472,2020-12-31,N53745100,0.0,0.0,3.56,0.006458,24.144495,13.502839,0.026655,0.0,...,0.296522,0.313991,92.00,34.9,-0.003696,1.626361,1.9500,0.63,LYB,NaN